version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: shop
      MONGO_INITDB_ROOT_USERNAME: mongokeeper
      MONGO_INITDB_ROOT_PASSWORD: mySecret!
    volumes:
      - ./src/main/resources/db/populate_data.js:/docker-entrypoint-initdb.d/populate_data.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongokeeper
      ME_CONFIG_MONGODB_ADMINPASSWORD: mySecret!
      ME_CONFIG_MONGODB_URL: mongodb://mongokeeper:mySecret!@mongo:27017/
